"""add submitted_by and submitter_ip audit fields

Revision ID: 7024a6a60ab4
Revises: 2b30ef74b27f
Create Date: 2026-09-12 07:39:56.837383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7024a6a60ab4'
down_revision: Union[str, Sequence[str], None] = '2b30ef74b27f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('submitted_by', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('submitter_ip', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'submitter_ip')
    op.drop_column('tasks', 'submitted_by')
    # ### end Alembic commands ###
